= {lab_name}

== Introduction

In this lab, we aim to demonstrate the value-added service available to customers who purchase OpenShift Platform Plus subscriptions, which can benefit enterprises that need to manage multiple cluster deployments in an organized and security-focused manner. OpenShift Platform Plus contains all of the features that you may be familiar with in a standard OpenShift Container Platform subscription, but with the bonus of including four additional components for advanced management and functionality:  

* Red Hat Advanced Cluster Management for Kubernetes (RHACM)
* Red Hat Advanced Cluster Security for Kubernetes (RHACS)
* Red Hat Quay (Quay)
* Red Hat OpenShift Data Foundation (RHODF)

In this lab, participants can expect to gain a comprehensive understanding of the advanced capabilities provided by making use of these products to perform such as setting up a private registry for hosting images, deploying clusters and setting up global policies to make cluster management more straightforward, and analyzing the security profile of their clusters and applications by creating application enforcement policies and viewing image and network graph information to understand possible vulnerabilities in their deployments. 

Overall, this workshop promises to be a valuable learning experience for anyone looking to expand their knowledge of the value provided by purchasing a subscription for OpenShift Platform Plus.

== OpenShift Platform Plus Components

=== Red Hat Advanced Cluster Management for Kubernetes (RHACM)

Red Hat Advanced Cluster Management for Kubernetes is a multi-cluster management solution that helps organizations manage their Kubernetes clusters and applications across hybrid and multicloud environments. It provides a unified management console, policy-based governance, observability, and automation capabilities, helping to simplify and streamline Kubernetes management operations.

In this workshop we will demonstrate the value of RHACM with the following activities:

. Demonstrate the ease of deploying new clusters in the cloud.
. Create an application deployment policy across managed clusters.
. Create a governance policy to help secure our clusters.

=== Red Hat Advanced Cluster Security for Kubernetes (RHACS)

Red Hat Advanced Cluster Security for Kubernetes is a Kubernetes-native security platform that equips you to build, deploy, and run cloud-native applications with more security. The solution helps protect containerized Kubernetes workloads in all major clouds and hybrid platforms, including Red Hat OpenShift, Amazon Elastic Kubernetes Service (EKS), Microsoft Azure Kubernetes Service (AKS), and Google Kubernetes Engine (GKE).

In this workshop we will demonstrate the value of RHACS with the following activities:

. Examine the RHACS console in order to explore vulnerable workloads.
. Explore network graphs and metrics created by observing applications running in the cluster.
. Demonstrate deployment and runtime enforcement options to prevent security issues.

=== Red Hat Quay (Quay)

Red Hat Quay is a security-focused and scalable private registry platform for managing content across globally distributed datacenter and cloud environments. It provides a single and resilient content repository for delivering containerized software to development and production across Red Hat OpenShift and Kubernetes clusters. Red Hat Quay is a distributed and highly available container image registry for your enterprise.

In this workshop we will demonstrate the value of Quay with the following activities:

. Easily Install and Configure Quay from the OpenShift OperatorHub.
. Configure a private registry for use with our clusters.
. Upload and explore an image with our newly created registry.

=== Red Hat OpenShift Data Foundation (RHODF)

Red Hat OpenShift Data Foundation—previously Red Hat OpenShift Container Storage—is software-defined storage for containers. Red Hat OpenShift Data Foundation helps teams develop and deploy applications quickly and efficiently across clouds.

NOTE: In this workshop we will not use ODF explicitly, but it will be used as the primary backing storage for our Quay registry, and any other applications we deploy in the cluster that need persistent storage.

== Environment Overview and Access

You will be interacting with an OpenShift 4 cluster that is running on Amazon Web Services. This cluster will act as a central hub for the actions you are performing in your environment.
The basics of the OpenShift 4 installation have been completed in advance. The OpenShift cluster is essentially set to all defaults and looks like the following:

. Three control-plane nodes
. Three worker nodes
. One bastion host

In addition you will have an additional working cluster provisioned with Hosted Control Planes in AWS, and be able to deploy your own cluster as a part of the lab tasks. 

=== Working Environment

All of the commands, walkthroughs, images, and warnings for the lab can be found in the this lab guide, called the "Showroom lab guide" 

[IMPORTANT]

=== OpenShift Console Access & RHACM console Access

The Red Hat Advanced Cluster Management for Kubernetes (RHACM) Console is now integrated with OpenShift Console, to access it please select *All Clusters* from the dropdown menu once you log in. 

Your OpenShift cluster console is available at: {openshift_console_url}

[cols="1,1"]
|===
OpenShift console URL | {openshift_console_url}
|===

Administrator login is available with:

[cols="1,1"]
|===
*User:*| kubeadmin |
*Password:*| {openshift_kubeadmin_password} |
|===

=== RHACS Console Access

Your RHACS Console is available at: {acs_route}[window=blank]

Administrator login is available with:

[cols="1,1"]
|===
*RHACS Console Username:* | {acs_portal_username} |
*RHACS Console Password:* | {acs_portal_password} |
|===

=== Red Hat Quay

Your Red Hat Quay Console is available at: {quay_console_url}[window=blank]

[cols="1,1"]
|===
*Quay Console Username:* | {quay_admin_username} |
*Quay Console Password:* | {quay_admin_password} |
*Quay Console URL"*      | {quay_console_url}    |
|===

=== Bastion Access

A RHEL bastion host is available with common utilities pre-installed and OpenShift command line access pre-configured.

For SSH access to the bastion:

[cols="1,1"]
|===
*Bastion Hostname:* | {bastion_public_hostname} |
*Bastion Username:* | {bastion_ssh_user_name} |
*Bastion Password:* | {bastion_ssh_password} |
|===

.Example bastion SSH command
[subs=attributes+]
----
ssh {bastion_ssh_user_name}@{bastion_public_hostname}
----

Make sure you use the username '{bastion_ssh_user_name}' and the password '{bastion_ssh_password}' when prompted.


