= {lab_name}

== Introduction

In this lab, we aim to demonstrate the value-added service available to customers who purchase OpenShift Platform Plus subscriptions, which can benefit enterprises that need to manage multiple cluster deployments in an organized and security-focused manner. OpenShift Platform Plus contains all of the features that you may be familiar with in a standard OpenShift Container Platform subscription, but with the bonus of including four additional components for advanced management and functionality:  

* Red Hat Advanced Cluster Management for Kubernetes (RHACM)
* Red Hat Advanced Cluster Security for Kubernetes (RHACS)
* Red Hat Quay (Quay)
* Red Hat OpenShift Data Foundation (RHODF)

In this lab, participants can expect to gain a comprehensive understanding of the advanced capabilities provided by making use of these products to perform such as setting up a private registry for hosting images, deploying clusters and setting up global policies to make cluster management more straightforward, and analyzing the security profile of their clusters and applications by creating application enforcement policies and viewing image and network graph information to understand possible vulnerabilities in their deployments. 

Overall, this workshop promises to be a valuable learning experience for anyone looking to expand their knowledge of the value provided by purchasing a subscription for OpenShift Platform Plus.

== OpenShift Platform Plus applications

=== Red Hat Advanced Cluster Management for Kubernetes (RHACM)

Red Hat Advanced Cluster Management for Kubernetes is a multi-cluster management solution that helps organizations manage their Kubernetes clusters and applications across hybrid and multicloud environments. It provides a unified management console, policy-based governance, observability, and automation capabilities, helping to simplify and streamline Kubernetes management operations.

In this workshop we will demonstrate the value of RHACM with the following activities:

. Demonstrate the ease of deploying new clusters in the cloud.
. Create an application deployment policy across managed clusters.
. Create a governance policy to help secure our clusters.

=== Red Hat Advanced Cluster Security for Kubernetes (RHACS)

Red Hat Advanced Cluster Security for Kubernetes is a Kubernetes-native security platform that equips you to build, deploy, and run cloud-native applications with more security. The solution helps protect containerized Kubernetes workloads in all major clouds and hybrid platforms, including Red Hat OpenShift, Amazon Elastic Kubernetes Service (EKS), Microsoft Azure Kubernetes Service (AKS), and Google Kubernetes Engine (GKE).

In this workshop we will demonstrate the value of RHACS with the following activities:

. Examine the RHACS console in order to explore vulnerable workloads.
. Explore network graphs and metrics created by observing applications running in the cluster.
. Demonstrate deployment and runtime enforcement options to prevent security issues.

=== Red Hat Quay (Quay)

Red Hat Quay is a security-focused and scalable private registry platform for managing content across globally distributed datacenter and cloud environments. It provides a single and resilient content repository for delivering containerized software to development and production across Red Hat OpenShift and Kubernetes clusters. Red Hat Quay is a distributed and highly available container image registry for your enterprise.

In this workshop we will demonstrate the value of Quay with the following activities:

. Easily Install and Configure Quay from the OpenShift OperatorHub.
. Configure a private registry for use with our clusters.
. Upload and explore an image with our newly created registry.

=== Red Hat OpenShift Data Foundation (RHODF)

Red Hat OpenShift Data Foundation—previously Red Hat OpenShift Container Storage—is software-defined storage for containers. Red Hat OpenShift Data Foundation helps teams develop and deploy applications quickly and efficiently across clouds.

NOTE: In this workshop we will not use ODF explicitly, but it will be used as the primary backing storage for our Quay registry, and any other applications we deploy in the cluster that need persistent storage.

== Environment Overview and Access

You will be interacting with an OpenShift 4 cluster that is running on Amazon Web Services. This cluster will act as a central hub for the actions you are performing in your environment.
The basics of the OpenShift 4 installation have been completed in advance. The OpenShift cluster is essentially set to all defaults and looks like the following:

. Three control-plane nodes
. Three worker nodes
. One bastion host

In addition you will have an additional working cluster provisioned with Hosted Control Planes in AWS, and be able to deploy your own cluster as a part of the lab tasks. 

=== Working Environment

IMPORTANT: All of the commands, walkthroughs, images, and warnings for the lab can be found in the this lab guide, called the "Showroom lab guide" 

====  OpenShift console access & RHACM console access

The Red Hat Advanced Cluster Management for Kubernetes (RHACM) Console is now integrated with OpenShift Console, to access it please select *All Clusters* from the dropdown menu once you log in. 

Your OpenShift cluster console is available at: {openshift_console_url}

[cols="1,1"]
|===
OpenShift console URL | {openshift_console_url}
|===

Administrator login is available with:

[cols="1,1"]
|===
*User:*| kubeadmin |
*Password:*| {openshift_kubeadmin_password} |
|===

==== RHACS console access

Your RHACS Console is available at: {acs_route}[window=blank]

Administrator login is available with:

[cols="1,1"]
|===
*RHACS Console Username:* | {acs_portal_username} |
*RHACS Console Password:* | {acs_portal_password} |
|===

==== Quay console access

Your Red Hat Quay console is available at: {quay_console_url}[window=blank]

[cols="1,1"]
|===
*Quay Console Username:* | {quay_admin_username} |
*Quay Console Password:* | {quay_admin_password} |
*Quay Console URL"*      | {quay_console_url}    |
|===

==== Bastion Access

A RHEL bastion host is available with common utilities pre-installed and OpenShift command line access pre-configured.

For SSH access to the bastion:

[cols="1,1"]
|===
*Bastion Hostname:* | {bastion_public_hostname} |
*Bastion Username:* | {bastion_ssh_user_name} |
*Bastion Password:* | {bastion_ssh_password} |
|===

.Enter the ssh command in the Showroom lab terminal

[source,sh,subs="attributes",role=execute]

----
ssh {bastion_ssh_user_name}@{bastion_public_hostname}
----

Make sure you use the password '{bastion_ssh_password}' when prompted.

== Demo applications setup

=== Download the "Java" application and push the container image to Quay via the Bastion VM

For a simple task to demonstrate the functionality of Quay, we can pull an image from a public respository and then upload it to our newly created private registry. For this purpose we are going to use the ctf-web-to-system container image.

IMPORTANT: You will need to complete the following commands in the *Bastion VM* Please SSH to it (If you have not already) by using the following command:

----
ssh {bastion_ssh_user_name}@{bastion_public_hostname}
----

Make sure you use the password '{bastion_ssh_password}' when prompted.

. First, let's export a few variable to make our life easier

[source,sh,subs="attributes",role=execute]

----
export QUAY_USER={quay_admin_username}
----

[start=2]

. Set the Quay URL variable but make to REMOVE the *https://*

[cols="1,1"]
|===
*Quay Console URL"*      | {quay_console_url}    |
|===

[source,sh,subs="attributes",role=execute]
----
export QUAY_URL={quay_console_url} #remove https://
----

[start=3]
. Using the terminal on the bastion host, login to quay using the Podman CLI as shown below:

[source,sh,subs="attributes",role=execute]
----
podman login $QUAY_URL
----

NOTE: Use the quay admin credentials, Username: *{quay_admin_username}* & password: *{quay_admin_password}*. You can create unique user and group credentials in Quay for proper segmentation. 

*Sample output*
[source,bash]
----
Username: quayadmin
Password:
Login Succeeded!
----

[start=4]
. Pull the Java container image with the following cli command:

[source,sh,subs="attributes",role=execute]
----
podman pull quay.io/jechoisec/ctf-web-to-system-01
----

*Sample output*
[source,bash]
----
Trying to pull podman pull quay.io/jechoisec/ctf-web-to-system-01...
Getting image source signatures
Copying blob d3c894b5b2b0 done
Copying blob 960043b8858c done
Copying blob eebb06941f3e done
Copying blob 5c984a731132 done
Copying blob 02cd68c0cbf6 done
Copying blob ac1099dcb77c done
Copying blob b40161cd83fc done
Copying blob 46ba3f23f1d3 done
Copying blob 4fa131a1b726 done
Copying blob 5f367a3bfdcf done
Copying blob 9667fec0b471 done
Copying blob 9b509fdf4970 done
Copying blob 546ce7892922 done
Copying blob 20dd98444fbf done
Copying blob b25c8b834f22 done
Copying blob 83fba0af389a done
Copying blob 4c27f8a9a616 done
Copying blob 7cbc0c1e2e4c done
Copying blob c0a01ea16cdd done
Copying config f5857a0685 done
Writing manifest to image destination
WARNING: image platform (linux/arm64/v8) does not match the expected platform (linux/amd64)
f5857a06852012a8f7eb9b464eac419ec03d31e810b4d48ae1ea86131cd81475
----

[start=5]
. Now that you have a copy of the Java container image locally. Let's tag the image and push it to our private registry using the following commands:

[source,sh,subs="attributes",role=execute]
----
podman tag quay.io/jechoisec/ctf-web-to-system-01 $QUAY_URL/$QUAY_USER/ctf-web-to-system:1.0
----

[source,sh,subs="attributes",role=execute]
----
podman push $QUAY_URL/$QUAY_USER/ctf-web-to-system:1.0 --remove-signatures
----

[start=6]

In the next module, we will browse through Quay to see the Java container app that you have tagged and pushed. The apple will be deployed into the cluster in the next step.

=== Deploy the demo applications

Our insecure demo applications come from a variety of public GitHub repositories and sources. Including the Java app that you just pushed to Quay. Let's deploy them into our cluster.

. Run the following command in the Bastion VM

[source,sh,subs="attributes",role=execute]
----
git clone https://github.com/mfosterrox/demo-apps.git roadshow-apps
export TUTORIAL_HOME="$(pwd)/roadshow-apps"
sed -i "s|quay.io/jechoisec/ctf-web-to-system-01|$QUAY_URL/$QUAY_USER/ctf-web-to-system:1.0|g" $TUTORIAL_HOME/kubernetes-manifests/ctf-web-to-system/ctf-w2s.yml
oc apply -f $TUTORIAL_HOME/kubernetes-manifests/ --recursive
oc apply -f $TUTORIAL_HOME/openshift-pipelines/ --recursive
----

[IMPORTANT]
You should see warnings such as: Warning: would violate PodSecurity "restricted:latest": unrestricted capabilities (container "ubi" must set securityContext.capabilities.drop=["ALL"] this is because we are deploying flawed container configurations and vulnerabile container applications into the OpenShift cluster.

[NOTE] This command applies a plethora of manifests to your environment. The important part is that the deployments are up and running. 

[start=2]
. Run the following command and ensure that the applications are up and running

[source,bash,role="execute"]
----
kubectl get deployments -l demo=roadshow -A
----

*Output*
```bash
NAMESPACE    NAME                    READY   UP-TO-DATE   AVAILABLE   AGE
backend      api-server              1/1     1            1           72m
default      adservice               1/1     1            1           67m
default      api-server              1/1     1            1           71m
default      cartservice             1/1     1            1           67m
default      checkoutservice         1/1     1            1           67m
default      ctf-web-to-system       1/1     1            1           72m
default      currencyservice         1/1     1            1           67m
default      emailservice            1/1     1            1           67m
default      frontend                1/1     1            1           71m
default      juice-shop              1/1     1            1           57m
default      loadgenerator           1/1     1            1           66m
default      paymentservice          1/1     1            1           66m
default      productcatalogservice   1/1     1            1           66m
default      rce                     1/1     1            1           71m
default      recommendationservice   1/1     1            1           66m
default      redis-cart              1/1     1            1           66m
default      reporting               1/1     1            1           71m
default      shippingservice         1/1     1            1           67m
frontend     asset-cache             1/1     1            1           71m
medical      reporting               1/1     1            1           71m
operations   jump-host               1/1     1            1           71m
payments     visa-processor          1/1     1            1           71m
```

[NOTE]
the main focus needs to be that the *ctf-web-to-system* application deployed properly. 


Nice Job! Please move onto the next module.
