= Setup

[[access]]

== Environment Setup and Access

[[openshift-acm]]

===  OpenShift console access & RHACM console access

NOTE: The Red Hat Advanced Cluster Management for Kubernetes (RHACM) Console is now integrated with OpenShift Console, to access it please select *All Clusters* from the dropdown menu once you log in. 

Your OpenShift cluster console is available at: {openshift_console_url}

Administrator login is available with:

[cols="1,1"]
|===
*User:*| kubeadmin |
*Password:*| {openshift_kubeadmin_password} |
|===

[[acs]]
=== RHACS console access

Your RHACS Console is available at: {acs_route}[window=blank]

Administrator login is available with:

[cols="1,1"]
|===
*RHACS Console Username:* | {acs_portal_username} |
*RHACS Console Password:* | {acs_portal_password} |
|===

[[quay]]

=== Quay console access

Your Red Hat Quay console is available at: {quay_console_url}[window=blank]

Administrator login is available with:

[cols="1,1"]
|===
*Quay Console Username:* | {quay_admin_username} |
*Quay Console Password:* | {quay_admin_password} |
|===

[[bastion-host]]

=== Bastion Access

A RHEL bastion host is available with common utilities pre-installed and OpenShift command line access pre-configured.

For SSH access to the bastion:

[cols="1,1"]
|===
*Bastion Hostname:* | {bastion_public_hostname} |
*Bastion Username:* | {bastion_ssh_user_name} |
*Bastion Password:* | {bastion_ssh_password} |
|===

. Enter the ssh command in the Showroom lab terminal

[source,sh,subs="attributes",role=execute]

----
ssh {bastion_ssh_user_name}@{bastion_public_hostname}
----

*Sample output*
[source,bash]
----
The authenticity of host 'ec2-18-218-57-221.us-east-2.compute.amazonaws.com ($IP_ADDRESS)' can't be established.
ED25519 key fingerprint is SHA256:X2AGqDUv+yVqYGGh0Ul8b8awRM0kWXgAAzePskZ6ixo.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])?
----

[start=2]
. Type "Yes"


. Enter the SSH password (*{bastion_ssh_password}*) when prompted.

[[demo-applications]]

== Demo applications setup

IMPORTANT: Make sure to finish all of the following steps and ensure the vulnerable applications deploy properly. We will use these applications in later modules. 

=== Download, build and push the Java demo container image to Quay via the Bastion VM

To demonstrate Quay's functionality, we can pull an image from a public repository and upload it to our newly created registry. We can push container images to Quay as long as we have the correct credentials to set up new registries. To demonstrate this functionality, we are going to use the ctf-web-to-system container image.

IMPORTANT: You will need to complete the following commands in the *Bastion VM* Please SSH to it (If you have not already) by using the following command:

[source,sh,subs="attributes",role=execute]

----
ssh {bastion_ssh_user_name}@{bastion_public_hostname}
----

Make sure you use the password '{bastion_ssh_password}' when prompted.

. Let's export a few variable to make our life easier

[source,sh,subs="attributes",role=execute]
----
export QUAY_USER={quay_admin_username}
----

[start=2]

. Set the Quay URL variable 

IMPORTANT: Make sure to REMOVE the *https://* from the URL command below.

[source,sh,subs="attributes",role=execute]
----
export QUAY_URL={quay_console_url} #remove https://
----

[start=3]
. Using the terminal on the bastion host, login to quay using the Podman CLI as shown below:

[source,sh,subs="attributes",role=execute]
----
podman login $QUAY_URL
----

NOTE: Use the quay admin credentials, Username: *{quay_admin_username}* & password: *{quay_admin_password}*. You can create unique user and group credentials in Quay for proper segmentation. 

*Sample output*
[source,bash]
----
Username: quayadmin
Password:
Login Succeeded!
----

[start=4]
. Pull the Java container image with the following CLI command:

[source,sh,subs="attributes",role=execute]
----
podman pull quay.io/jechoisec/ctf-web-to-system-01
----

*Sample output*
[source,bash]
----
Trying to pull quay.io/jechoisec/ctf-web-to-system-01:latest...
Getting image source signatures
Copying blob 37aaf24cf781 done 
...
...
Copying config 1cbb2b7908 done  
Writing manifest to image destination
1cbb2b79086961e34d06f301b2fa15d2a7e359e49cfe67c06b6227f6f0005149
----

[start=5]
. Now that you have a copy of the Java container image locally. You must tag the image before pushing it to Quay. 

[source,sh,subs="attributes",role=execute]
----
podman tag quay.io/jechoisec/ctf-web-to-system-01 $QUAY_URL/$QUAY_USER/ctf-web-to-system:1.0
----

NOTE: Quay will automatically create a private registry to store our Java appplication. We will need to make it a public repository to be able to pull the miage without credentials. We will do this in the following module

[start=6]
. The last step is to push the image to Quay.

[source,sh,subs="attributes",role=execute]
----
podman push $QUAY_URL/$QUAY_USER/ctf-web-to-system:1.0 --remove-signatures
----

*Sample output*
[source,bash]
----
Copying blob 3113fb957b33 done 
...
...
Copying config 1cbb2b7908 done  
Writing manifest to image destination
----

[start=6]

Perfect!

In the next module, we will browse through Quay to see the Java container app that you have tagged and pushed. The apple will be deployed into the cluster in the next step.

